In [1]:
from pathlib import Path

from vascx.fundus.loader import RetinaLoader
from vascx.utils.analysis import (
    extract_in_parallel,
)

In [2]:
ds_path = Path("../samples/fundus")

In [3]:
loader = RetinaLoader.from_folder(ds_path)

Folder av_path: 6 files
Folder disc_path: 6 files
Folder fundus_path: 6 files
Folder vessels_path: 6 files

In [4]:
res = extract_in_parallel(loader.to_dict(), "full_v3", n_jobs=1, print_stack_trace=True)

Extracting features for 6 examples

In [5]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.403042,21.699569,7.710585,11.139406,12.655233,19.488305,13.338037,18.550685,16.390819,26.129413
CHASEDB1_12R,15.378857,20.712671,12.539873,14.105750,11.938203,16.627512,14.274060,17.248444,19.499556,25.623709
DRIVE_22,11.770071,14.928247,9.907374,10.034174,8.978830,12.121747,NaN,NaN,NaN,NaN
DRIVE_40,12.045553,19.175800,8.643181,14.534771,10.607464,14.056028,NaN,NaN,NaN,NaN
HRF_04_g,6.906211,11.241557,5.689400,8.592872,5.396474,7.951992,4.851498,7.205617,7.507024,12.750285
HRF_07_dr,8.456356,13.591429,6.365446,10.409339,7.194545,9.858852,7.537545,9.619323,10.390374,15.670040

In [5]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.403042,21.699569,7.710585,11.139406,12.655233,19.488305,13.338037,18.550685,16.390819,26.129413
CHASEDB1_12R,15.378857,20.712671,12.539873,14.105750,11.938203,16.627512,14.274060,17.248444,19.499556,25.623709
DRIVE_22,11.770071,14.928247,9.907374,10.034174,8.978830,12.121747,NaN,NaN,NaN,NaN
DRIVE_40,12.045553,19.175800,8.643181,14.534771,10.607464,14.056028,NaN,NaN,NaN,NaN
HRF_04_g,6.906211,11.241557,5.689400,8.592872,5.396474,7.951992,4.851498,7.205617,7.507024,12.750285
HRF_07_dr,8.170901,13.591429,5.801948,10.409339,7.194545,9.858852,7.537545,9.619323,10.204270,15.670040

In [8]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.403042,21.699569,7.710585,11.139406,12.655233,19.488305,13.338037,18.550685,16.390819,26.129413
CHASEDB1_12R,15.378857,20.712671,12.539873,14.105750,11.938203,16.627512,14.274060,17.248444,19.499556,25.623709
DRIVE_22,11.770071,14.928247,9.907374,10.034174,8.978830,12.121747,NaN,NaN,NaN,NaN
DRIVE_40,12.045553,19.175800,8.643181,14.534771,10.607464,14.056028,NaN,NaN,NaN,NaN
HRF_04_g,6.906211,11.241557,5.689400,8.592872,5.396474,7.951992,4.851498,7.205617,7.507024,12.750285
HRF_07_dr,8.170901,13.591429,5.801948,10.409339,7.194545,9.858852,7.537545,9.619323,10.204270,15.670040

In [7]:
res.describe()

,mn_bifangle_arteries,mn_bifangle_veins,mn_bifangle_hf_superior_arteries,mn_bifangle_hf_superior_veins,mn_bifangle_hf_inferior_arteries,mn_bifangle_hf_inferior_veins,md_diam_arteries,md_diam_veins,md_diam_hf_superior_arteries,md_diam_hf_superior_veins,...,mean_sparsity_elps_full_vessels,max_sparsity_elps_full_vessels,mean_sparsity_disc_full_vessels,max_sparsity_disc_full_vessels,mean_sparsity_etdrs_full_vessels,max_sparsity_etdrs_full_vessels,lapl_retina,lapl_elps_full_retina,lapl_disc_full_retina,lapl_etdrs_full_retina
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,...,6.000000,6.000000,6.000000,6.000000,6.000000,5.000000,6.000000,6.000000,6.000000,6.000000
mean,83.841029,80.269631,82.542831,81.384434,85.563171,79.124055,3.928372,3.820302,4.089939,3.680715,...,0.043984,0.144434,0.044536,0.152766,0.042701,0.121922,12.375323,14.570287,13.945270,12.531897
std,5.555154,3.938238,4.498377,7.775211,8.079264,2.618570,1.340108,0.999590,1.321800,0.608178,...,0.006595,0.028865,0.008118,0.042751,0.006287,0.028024,8.411013,11.327246,9.715492,9.469308
min,75.146638,76.066566,76.335765,70.694712,73.838599,74.964968,2.217357,2.357058,2.161499,2.933049,...,0.038646,0.110125,0.035505,0.097746,0.036150,0.099437,6.005736,6.371322,6.267856,5.366138
25%,82.014933,76.909758,79.270477,76.430660,82.342408,77.931497,3.093926,3.145157,3.390344,3.163928,...,0.039082,0.117678,0.040315,0.121872,0.038645,0.105856,6.465974,7.288008,7.010918,5.966469
50%,83.662614,79.968516,83.286284,81.553169,84.859224,79.363267,3.777059,4.108170,4.172232,3.892099,...,0.041269,0.152926,0.041884,0.161945,0.041153,0.110546,8.885737,10.254131,11.202998,9.082998
75%,86.563474,83.006969,85.891065,88.104434,89.065188,81.039124,4.730982,4.527458,4.808337,4.009767,...,0.047496,0.168646,0.047963,0.169804,0.045231,0.124502,15.302534,16.186500,15.910891,14.838616
max,91.578177,85.704228,87.657454,89.494208,97.851335,82.000843,5.883583,4.857040,5.883583,4.396848,...,0.054793,0.170813,0.058159,0.214020,0.053349,0.169268,27.373873,36.078882,31.904020,29.974471

In [6]:
res.loc[:,[col for col in res.columns if 'diam' in col]]

,md_diam_arteries,md_diam_veins,md_diam_hf_superior_arteries,md_diam_hf_superior_veins,md_diam_hf_inferior_arteries,md_diam_hf_inferior_veins,lw_diam_arteries,lw_diam_veins,lw_diam_hf_superior_arteries,lw_diam_hf_superior_veins,lw_diam_hf_inferior_arteries,lw_diam_hf_inferior_veins
CHASEDB1_08L,4.896477,4.857040,4.171007,4.396848,6.021301,6.069380,6.543162,7.831008,5.558651,7.775976,8.298361,8.449187
CHASEDB1_12R,5.883583,4.201512,5.883583,3.855915,5.914565,5.080394,7.269843,7.304933,7.572524,7.033141,6.988148,7.609210
DRIVE_22,3.319621,4.014828,5.019964,3.928282,3.223695,4.444523,5.048790,5.615715,5.256499,5.455658,5.011757,5.881528
DRIVE_40,4.234497,4.636106,4.173458,4.036929,4.264058,5.100440,5.741378,6.481441,5.794389,6.467066,5.695767,6.495927
HRF_04_g,2.217357,2.357058,2.161499,2.933266,2.380616,2.088946,3.090393,3.810587,3.114667,3.979627,3.096505,3.686665
HRF_07_dr,3.018694,2.855267,3.130123,2.933049,2.612398,2.912875,3.773195,4.353580,3.875073,4.200548,3.682117,4.587042

In [7]:
res.columns

Index(['mn_bifangle_arteries', 'mn_bifangle_veins',
       'mn_bifangle_hf_superior_arteries', 'mn_bifangle_hf_superior_veins',
       'mn_bifangle_hf_inferior_arteries', 'mn_bifangle_hf_inferior_veins',
       'md_diam_arteries', 'md_diam_veins', 'md_diam_hf_superior_arteries',
       'md_diam_hf_superior_veins', 'md_diam_hf_inferior_arteries',
       'md_diam_hf_inferior_veins', 'lw_diam_arteries', 'lw_diam_veins',
       'lw_diam_hf_superior_arteries', 'lw_diam_hf_superior_veins',
       'lw_diam_hf_inferior_arteries', 'lw_diam_hf_inferior_veins',
       'temporal_cre_arteries', 'temporal_cre_veins',
       'temporal_cre_hf_superior_arteries', 'temporal_cre_hf_superior_veins',
       'temporal_cre_hf_inferior_arteries', 'temporal_cre_hf_inferior_veins',
       'nasal_cre_arteries', 'nasal_cre_veins', 'full_cre_arteries',
       'full_cre_veins', 'md_tort_dist_arteries', 'md_tort_dist_veins',
       'md_tort_curv_arteries', 'md_tort_curv_veins', 'lw_tort_dist_arteries',
       'lw_tort_dist_veins', 'lw_tort_curv_arteries', 'lw_tort_curv_veins',
       'md_tort_dist_etdrs_full_arteries', 'md_tort_dist_etdrs_full_veins',
       'md_tort_curv_etdrs_full_arteries', 'md_tort_curv_etdrs_full_veins',
       'lw_tort_dist_etdrs_full_arteries', 'lw_tort_dist_etdrs_full_veins',
       'lw_tort_curv_etdrs_full_arteries', 'lw_tort_curv_etdrs_full_veins',
       'vd_elps_full_arteries', 'vd_elps_full_veins', 'vd_disc_full_arteries',
       'vd_disc_full_veins', 'vd_etdrs_full_arteries', 'vd_etdrs_full_veins',
       'vd_hf_superior_arteries', 'vd_hf_superior_veins',
       'vd_hf_inferior_arteries', 'vd_hf_inferior_veins',
       'disc_fovea_distance_retina', 'mean_sparsity_vessels',
       'max_sparsity_vessels', 'mean_sparsity_elps_full_vessels',
       'max_sparsity_elps_full_vessels', 'mean_sparsity_disc_full_vessels',
       'max_sparsity_disc_full_vessels', 'mean_sparsity_etdrs_full_vessels',
       'max_sparsity_etdrs_full_vessels', 'lapl_retina',
       'lapl_elps_full_retina', 'lapl_disc_full_retina',
       'lapl_etdrs_full_retina'],
      dtype='object')

In [8]:
res.loc['CHASEDB1_08L',:]

mn_bifangle_arteries                81.507757
mn_bifangle_veins                   81.508166
mn_bifangle_hf_superior_arteries    78.263489
mn_bifangle_hf_superior_veins       86.075873
mn_bifangle_hf_inferior_arteries    83.940958
                                      ...
max_sparsity_etdrs_full_vessels      0.169268
lapl_retina                          7.037933
lapl_elps_full_retina                8.217920
lapl_disc_full_retina                8.911155
lapl_etdrs_full_retina               6.955609
Name: CHASEDB1_08L, Length: 67, dtype: float64