In [1]:
from pathlib import Path

from vascx.fundus.loader import RetinaLoader
from vascx.utils.analysis import (
    extract_in_parallel,
)

In [2]:
ds_path = Path("../samples/fundus")

In [3]:
loader = RetinaLoader.from_folder(ds_path)

Folder av_path: 6 files
Folder disc_path: 6 files
Folder fundus_path: 6 files
Folder vessels_path: 6 files

In [4]:
res = extract_in_parallel(loader.to_dict(), "full_v2", n_jobs=1, print_stack_trace=True)

  0%|          | 0/6 [00:00<?, ?it/s][Parallel(n_jobs=1)]: Done   1 tasks      | elapsed:    5.8s
 17%|█▋        | 1/6 [00:05<00:28,  5.77s/it]

 Example CHASEDB1_08L:: Could not find intersecting segmentes for CRE circle.

 50%|█████     | 3/6 [00:13<00:12,  4.15s/it][Parallel(n_jobs=1)]: Done   4 tasks      | elapsed:   16.6s
 67%|██████▋   | 4/6 [00:16<00:07,  3.84s/it]

 Example DRIVE_40:: Could not find intersecting segmentes for CRE circle.
 Example DRIVE_40:: Could not find intersecting segmentes for CRE circle.

100%|██████████| 6/6 [00:24<00:00,  4.13s/it]
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   24.8s finished

In [5]:
res

,angles_arteries,angles_veins,angles_sup_arteries,angles_sup_veins,angles_inf_arteries,angles_inf_veins,bif_arteries,bif_veins,bif_sup_arteries,bif_sup_veins,...,tort_dist_etdrs_norm_veins,tort_curv_etdrs_norm_arteries,tort_curv_etdrs_norm_veins,vd_arteries,vd_veins,vd_sup_arteries,vd_sup_veins,vd_inf_arteries,vd_inf_veins,odfd_image
CHASEDB1_08L,74.475889,79.750616,73.720327,76.478850,84.316259,86.987212,17,27,8,16,...,1.047782,5.611754,4.075128,0.053072,0.066937,0.046736,0.050202,0.042911,0.063213,396.526005
CHASEDB1_12R,90.083521,84.093859,90.167043,79.759058,90.000000,84.093859,20,24,10,13,...,1.049802,7.530104,6.290217,0.065114,0.069070,0.054857,0.056326,0.060600,0.061287,448.636980
DRIVE_22,85.408040,83.103916,93.756072,90.209317,82.174531,80.484895,24,39,11,21,...,1.154475,6.957527,16.272496,0.056577,0.075248,0.040300,0.053563,0.047299,0.057807,381.978783
DRIVE_40,86.546684,83.345575,83.531246,90.000000,96.766175,78.443370,21,34,14,18,...,1.591608,3.311006,6.067678,0.060027,0.076273,0.044313,0.062390,0.051895,0.066974,408.840120
HRF_04_g,71.296059,76.126297,68.242222,72.349876,75.018367,81.626048,27,29,15,17,...,1.073102,3.568747,4.692551,0.045245,0.060434,0.035615,0.046810,0.035597,0.038691,281.885440
HRF_07_dr,88.058514,75.348896,87.190993,73.570806,88.058514,76.420835,36,34,20,17,...,1.054549,4.453147,5.897639,0.067224,0.066634,0.054216,0.049611,0.047643,0.055111,307.165491

In [7]:
res[[col for col in res.columns if col.startswith('cre')]]

,cre_temporal_arteries,cre_temporal_veins,cre_temporal_sup_arteries,cre_temporal_sup_veins,cre_temporal_inf_arteries,cre_temporal_inf_veins,cre_nasal_arteries,cre_nasal_veins,cre_full_arteries,cre_full_veins
CHASEDB1_08L,11.834037,22.300624,7.448101,13.336258,12.113628,19.808482,13.266169,18.452161,15.938586,26.449662
CHASEDB1_12R,15.331529,20.447283,12.230414,15.082549,12.012428,15.468838,14.673318,17.329415,19.536693,25.185051
DRIVE_22,11.961512,14.853086,10.141342,9.785175,9.039219,12.137930,7.535539,11.154354,12.709641,17.777268
DRIVE_40,12.086044,19.280683,8.778216,14.757869,10.556141,14.230342,9.458625,5.337401,13.397677,19.291831
HRF_04_g,6.890131,11.572542,5.850464,8.550958,5.451718,8.494578,4.549289,7.029213,7.455019,12.796731
HRF_07_dr,8.343327,13.422484,6.411233,10.331352,6.984731,9.677967,7.623827,10.097891,10.329218,15.654552