In [1]:
from pathlib import Path

from vascx.fundus.loader import RetinaLoader
from vascx.utils.analysis import (
    extract_in_parallel,
)

In [2]:
ds_path = Path("../samples/fundus")

In [3]:
loader = RetinaLoader.from_folder(ds_path)

Folder av_path: 6 files
Folder disc_path: 6 files
Folder fundus_path: 6 files
Folder vessels_path: 6 files

In [4]:
res = extract_in_parallel(loader.to_dict(), "full_v3", n_jobs=1, print_stack_trace=True)

In [5]:
res

,mn_bifangle_arteries,mn_bifangle_veins,mn_bifangle_hf_superior_arteries,mn_bifangle_hf_superior_veins,mn_bifangle_hf_inferior_arteries,mn_bifangle_hf_inferior_veins,md_diam_arteries,md_diam_veins,md_diam_hf_superior_arteries,md_diam_hf_superior_veins,...,vd_hf_inferior_veins,disc_fovea_distance_retina,mean_sparsity_vessels,max_sparsity_vessels,mean_sparsity_elps_full_vessels,max_sparsity_elps_full_vessels,mean_sparsity_disc_full_vessels,max_sparsity_disc_full_vessels,mean_sparsity_etdrs_full_vessels,max_sparsity_etdrs_full_vessels
CHASEDB1_08L,81.312910,81.508166,78.263489,86.075873,83.599977,78.245518,5.218191,4.542920,4.718385,4.340195,...,0.063037,397.792988,0.056457,0.213339,0.054700,0.168729,0.057955,0.213339,0.053151,0.168729
CHASEDB1_12R,87.760760,76.403389,84.880368,70.694712,90.161087,80.481015,6.050536,4.285554,6.050536,3.695420,...,0.061248,448.629804,0.042661,0.193218,0.040155,0.110127,0.041112,0.110127,0.043217,NaN
DRIVE_22,83.788767,85.704228,86.427712,89.494208,81.809558,81.225160,3.316125,4.014828,5.019442,3.928282,...,0.057811,381.584045,0.042544,0.166777,0.042376,0.166777,0.042650,0.166777,0.038504,0.124502
DRIVE_40,93.075242,83.699078,90.150294,88.780621,98.340149,78.226647,4.219626,4.414293,4.127589,4.000920,...,0.067026,409.236411,0.039974,0.145305,0.038809,0.139005,0.035672,0.097651,0.036077,0.105753
HRF_04_g,75.282637,78.102542,76.595398,75.703588,73.838599,82.000843,2.315608,2.313513,2.164258,3.013325,...,0.038731,282.286816,0.050731,0.194192,0.049242,0.171363,0.049622,0.171363,0.046014,0.100759
HRF_07_dr,83.536460,75.176215,82.291444,75.772070,85.777490,74.537799,3.023691,2.839586,3.130123,2.855267,...,0.055046,306.241780,0.039741,0.157587,0.038770,0.110879,0.040170,0.157587,0.039161,0.110879

In [6]:
res.loc[:,[col for col in res.columns if 'tort' in col]]

,md_tort_dist_arteries,md_tort_dist_veins,md_tort_curv_arteries,md_tort_curv_veins,lw_tort_dist_arteries,lw_tort_dist_veins,lw_tort_curv_arteries,lw_tort_curv_veins,md_tort_dist_etdrs_full_arteries,md_tort_dist_etdrs_full_veins,md_tort_curv_etdrs_full_arteries,md_tort_curv_etdrs_full_veins,lw_tort_dist_etdrs_full_arteries,lw_tort_dist_etdrs_full_veins,lw_tort_curv_etdrs_full_arteries,lw_tort_curv_etdrs_full_veins
CHASEDB1_08L,1.010842,1.011400,3.924004,3.501958,1.017577,1.023306,3.279945,3.271496,1.009206,1.016852,5.695342,4.483044,1.043479,1.045002,6.062160,4.708207
CHASEDB1_12R,1.021902,1.017286,5.377983,4.545567,1.044336,1.032709,5.224353,4.382822,1.017812,1.018266,6.513345,6.241587,1.040825,1.044967,8.084502,6.248908
DRIVE_22,1.029843,1.058553,4.965268,10.873327,1.050210,1.111448,5.144217,12.109285,1.052465,1.072477,7.728538,14.477784,1.056772,1.137248,7.216840,16.425217
DRIVE_40,1.016169,1.014004,3.945184,4.419361,1.054707,1.036585,3.809994,4.304992,1.016169,1.017661,3.891760,5.431229,1.041458,1.059938,3.549945,6.051990
HRF_04_g,1.009890,1.016088,2.386729,3.290668,1.023290,1.031992,2.213957,3.336235,1.022909,1.032584,3.933007,4.475919,1.050914,1.068984,3.857404,4.796996
HRF_07_dr,1.024435,1.021093,3.499742,4.666611,1.038792,1.031992,3.398680,4.724286,1.051758,1.036488,3.828193,6.430300,1.071591,1.046442,4.271610,6.714149

In [7]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.622454,20.977999,7.971322,11.203832,12.809956,18.363660,13.406495,18.721541,16.507159,25.553137
CHASEDB1_12R,15.600070,20.188969,12.433124,14.206146,12.339442,15.752581,14.427770,17.272086,19.727808,25.195921
DRIVE_22,11.842395,15.073163,9.952250,10.217914,9.050488,12.164250,NaN,NaN,NaN,NaN
DRIVE_40,12.057938,19.071730,8.640754,14.656057,10.627585,13.768801,NaN,NaN,NaN,NaN
HRF_04_g,6.876116,11.294266,5.742569,8.650525,5.289440,7.985865,4.912428,7.537926,7.719875,12.904363
HRF_07_dr,8.447367,13.823191,6.348182,10.706563,7.196313,9.859111,7.558936,9.515785,10.399542,15.831310

In [8]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.622454,20.977999,7.971322,11.203832,12.809956,18.363660,13.406495,18.721541,16.507159,25.553137
CHASEDB1_12R,15.600070,20.188969,12.433124,14.206146,12.339442,15.752581,14.427770,17.272086,19.727808,25.195921
DRIVE_22,11.842395,15.073163,9.952250,10.217914,9.050488,12.164250,NaN,NaN,NaN,NaN
DRIVE_40,12.057938,19.071730,8.640754,14.656057,10.627585,13.768801,NaN,NaN,NaN,NaN
HRF_04_g,6.876116,11.294266,5.742569,8.650525,5.289440,7.985865,4.912428,7.537926,7.719875,12.904363
HRF_07_dr,8.447367,13.823191,6.348182,10.706563,7.196313,9.859111,7.558936,9.515785,10.399542,15.831310

In [8]:
res.loc[:,[col for col in res.columns if 'cre' in col]]

,temporal_cre_arteries,temporal_cre_veins,temporal_cre_hf_superior_arteries,temporal_cre_hf_superior_veins,temporal_cre_hf_inferior_arteries,temporal_cre_hf_inferior_veins,nasal_cre_arteries,nasal_cre_veins,full_cre_arteries,full_cre_veins
CHASEDB1_08L,12.403042,21.699569,7.710585,11.139406,12.655233,19.488305,13.338037,18.550685,16.390819,26.129413
CHASEDB1_12R,15.378857,20.712671,12.539873,14.105750,11.938203,16.627512,14.274060,17.248444,19.499556,25.623709
DRIVE_22,11.770071,14.928247,9.907374,10.034174,8.978830,12.121747,NaN,NaN,NaN,NaN
DRIVE_40,12.045553,19.175800,8.643181,14.534771,10.607464,14.056028,NaN,NaN,NaN,NaN
HRF_04_g,6.906211,11.241557,5.689400,8.592872,5.396474,7.951992,4.851498,7.205617,7.507024,12.750285
HRF_07_dr,8.170901,13.591429,5.801948,10.409339,7.194545,9.858852,7.537545,9.619323,10.204270,15.670040

In [7]:
res.describe()

,mn_bifangle_arteries,mn_bifangle_veins,mn_bifangle_hf_superior_arteries,mn_bifangle_hf_superior_veins,mn_bifangle_hf_inferior_arteries,mn_bifangle_hf_inferior_veins,md_diam_arteries,md_diam_veins,md_diam_hf_superior_arteries,md_diam_hf_superior_veins,...,mean_sparsity_elps_full_vessels,max_sparsity_elps_full_vessels,mean_sparsity_disc_full_vessels,max_sparsity_disc_full_vessels,mean_sparsity_etdrs_full_vessels,max_sparsity_etdrs_full_vessels,lapl_retina,lapl_elps_full_retina,lapl_disc_full_retina,lapl_etdrs_full_retina
count,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,...,6.000000,6.000000,6.000000,6.000000,6.000000,5.000000,6.000000,6.000000,6.000000,6.000000
mean,83.841029,80.269631,82.542831,81.384434,85.563171,79.124055,3.928372,3.820302,4.089939,3.680715,...,0.043984,0.144434,0.044536,0.152766,0.042701,0.121922,12.375323,14.570287,13.945270,12.531897
std,5.555154,3.938238,4.498377,7.775211,8.079264,2.618570,1.340108,0.999590,1.321800,0.608178,...,0.006595,0.028865,0.008118,0.042751,0.006287,0.028024,8.411013,11.327246,9.715492,9.469308
min,75.146638,76.066566,76.335765,70.694712,73.838599,74.964968,2.217357,2.357058,2.161499,2.933049,...,0.038646,0.110125,0.035505,0.097746,0.036150,0.099437,6.005736,6.371322,6.267856,5.366138
25%,82.014933,76.909758,79.270477,76.430660,82.342408,77.931497,3.093926,3.145157,3.390344,3.163928,...,0.039082,0.117678,0.040315,0.121872,0.038645,0.105856,6.465974,7.288008,7.010918,5.966469
50%,83.662614,79.968516,83.286284,81.553169,84.859224,79.363267,3.777059,4.108170,4.172232,3.892099,...,0.041269,0.152926,0.041884,0.161945,0.041153,0.110546,8.885737,10.254131,11.202998,9.082998
75%,86.563474,83.006969,85.891065,88.104434,89.065188,81.039124,4.730982,4.527458,4.808337,4.009767,...,0.047496,0.168646,0.047963,0.169804,0.045231,0.124502,15.302534,16.186500,15.910891,14.838616
max,91.578177,85.704228,87.657454,89.494208,97.851335,82.000843,5.883583,4.857040,5.883583,4.396848,...,0.054793,0.170813,0.058159,0.214020,0.053349,0.169268,27.373873,36.078882,31.904020,29.974471

In [6]:
res.loc[:,[col for col in res.columns if 'diam' in col]]

,md_diam_arteries,md_diam_veins,md_diam_hf_superior_arteries,md_diam_hf_superior_veins,md_diam_hf_inferior_arteries,md_diam_hf_inferior_veins,lw_diam_arteries,lw_diam_veins,lw_diam_hf_superior_arteries,lw_diam_hf_superior_veins,lw_diam_hf_inferior_arteries,lw_diam_hf_inferior_veins
CHASEDB1_08L,4.896477,4.857040,4.171007,4.396848,6.021301,6.069380,6.543162,7.831008,5.558651,7.775976,8.298361,8.449187
CHASEDB1_12R,5.883583,4.201512,5.883583,3.855915,5.914565,5.080394,7.269843,7.304933,7.572524,7.033141,6.988148,7.609210
DRIVE_22,3.319621,4.014828,5.019964,3.928282,3.223695,4.444523,5.048790,5.615715,5.256499,5.455658,5.011757,5.881528
DRIVE_40,4.234497,4.636106,4.173458,4.036929,4.264058,5.100440,5.741378,6.481441,5.794389,6.467066,5.695767,6.495927
HRF_04_g,2.217357,2.357058,2.161499,2.933266,2.380616,2.088946,3.090393,3.810587,3.114667,3.979627,3.096505,3.686665
HRF_07_dr,3.018694,2.855267,3.130123,2.933049,2.612398,2.912875,3.773195,4.353580,3.875073,4.200548,3.682117,4.587042

In [7]:
res.columns

Index(['mn_bifangle_arteries', 'mn_bifangle_veins',
       'mn_bifangle_hf_superior_arteries', 'mn_bifangle_hf_superior_veins',
       'mn_bifangle_hf_inferior_arteries', 'mn_bifangle_hf_inferior_veins',
       'md_diam_arteries', 'md_diam_veins', 'md_diam_hf_superior_arteries',
       'md_diam_hf_superior_veins', 'md_diam_hf_inferior_arteries',
       'md_diam_hf_inferior_veins', 'lw_diam_arteries', 'lw_diam_veins',
       'lw_diam_hf_superior_arteries', 'lw_diam_hf_superior_veins',
       'lw_diam_hf_inferior_arteries', 'lw_diam_hf_inferior_veins',
       'temporal_cre_arteries', 'temporal_cre_veins',
       'temporal_cre_hf_superior_arteries', 'temporal_cre_hf_superior_veins',
       'temporal_cre_hf_inferior_arteries', 'temporal_cre_hf_inferior_veins',
       'nasal_cre_arteries', 'nasal_cre_veins', 'full_cre_arteries',
       'full_cre_veins', 'md_tort_dist_arteries', 'md_tort_dist_veins',
       'md_tort_curv_arteries', 'md_tort_curv_veins', 'lw_tort_dist_arteries',
       'lw_tort_dist_veins', 'lw_tort_curv_arteries', 'lw_tort_curv_veins',
       'md_tort_dist_etdrs_full_arteries', 'md_tort_dist_etdrs_full_veins',
       'md_tort_curv_etdrs_full_arteries', 'md_tort_curv_etdrs_full_veins',
       'lw_tort_dist_etdrs_full_arteries', 'lw_tort_dist_etdrs_full_veins',
       'lw_tort_curv_etdrs_full_arteries', 'lw_tort_curv_etdrs_full_veins',
       'vd_elps_full_arteries', 'vd_elps_full_veins', 'vd_disc_full_arteries',
       'vd_disc_full_veins', 'vd_etdrs_full_arteries', 'vd_etdrs_full_veins',
       'vd_hf_superior_arteries', 'vd_hf_superior_veins',
       'vd_hf_inferior_arteries', 'vd_hf_inferior_veins',
       'disc_fovea_distance_retina', 'mean_sparsity_vessels',
       'max_sparsity_vessels', 'mean_sparsity_elps_full_vessels',
       'max_sparsity_elps_full_vessels', 'mean_sparsity_disc_full_vessels',
       'max_sparsity_disc_full_vessels', 'mean_sparsity_etdrs_full_vessels',
       'max_sparsity_etdrs_full_vessels', 'lapl_retina',
       'lapl_elps_full_retina', 'lapl_disc_full_retina',
       'lapl_etdrs_full_retina'],
      dtype='object')

In [8]:
res.loc['CHASEDB1_08L',:]

mn_bifangle_arteries                81.507757
mn_bifangle_veins                   81.508166
mn_bifangle_hf_superior_arteries    78.263489
mn_bifangle_hf_superior_veins       86.075873
mn_bifangle_hf_inferior_arteries    83.940958
                                      ...
max_sparsity_etdrs_full_vessels      0.169268
lapl_retina                          7.037933
lapl_elps_full_retina                8.217920
lapl_disc_full_retina                8.911155
lapl_etdrs_full_retina               6.955609
Name: CHASEDB1_08L, Length: 67, dtype: float64